# -*- coding: utf-8 -*-
"""AlunoMedia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODa8tTZHaU_rjprwwT8MFDh99dKzPlPQ
"""

aluno = input("Digite o nome do aluno: ")
n1 = int(input("Digite a primeira nota: "))
n2 = int(input("Digite a segunda nota: "))
n3 = int(input("Digite a terceira nota: "))